services:
  elimika-postgres:
    image: postgres:latest
    container_name: elimika-postgres
    environment:
      - POSTGRES_DB=elimika
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - elimika

  elimika-keycloak:
    image: quay.io/keycloak/keycloak:26.0.5
    container_name: elimika-keycloak
    ports:
      - "9090:8080"
    environment:
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://elimika-postgres:5432/keycloak
      - KC_DB_USERNAME=postgres
      - KC_DB_PASSWORD=postgres
    networks:
      - elimika
    command:
      - "start"
    restart: unless-stopped
    depends_on:
      - elimika-postgres

networks:
  elimika:
    driver: bridge

volumes:
  db_data:
    name: elimika-database-data