spring:

  # database configuration
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/elimika}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:admin}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    clean-disabled: false
    validate-on-migrate: true

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://signin.sarafrika.com/realms/elimika
          jwk-set-uri: https://signin.sarafrika.com/realms/elimika/protocol/openid-connect/certs

server:
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 2048

app:
  keycloak:
    admin:
      clientId: ${KC_PROD_CLIENT_ID:elimika}
      clientSecret: ${KC_PROD_CLIENT_SECRET:VzIw2uVpdLItRC0KNQF47vApi84sdmTz}
    realm: ${KC_PROD_REALM:elimika}
    serverUrl: ${SERVER_URL:https://signin.sarafrika.com}

encryption:
  secret-key: "986114de17023120b40eb549e17b11eaf080f14404f62b5ab994a538879b0c6b"
  salt: "364d2cdca2a27d02d4de972e752bdb8f"