spring:

  # database configuration
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/elimika}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:admin}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true
  flyway:
    clean-disabled: false
    validate-on-migrate: true

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:9090/realms/blast-wave
          jwk-set-uri: http://localhost:9090/realms/blast-wave/protocol/openid-connect/certs

server:
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 2048



app:
  keycloak:
    admin:
      clientId: ${KC_PROD_CLIENT_ID}
      clientSecret: ${KC_PROD_CLIENT_SECRET}
    realm: ${KC_PROD_REALM}
    serverUrl: ${KC_PROD_SERVER_URL}

encryption:
  secret-key: "986114de17023120b40eb549e17b11eaf080f14404f62b5ab994a538879b0c6b"
  salt: "364d2cdca2a27d02d4de972e752bdb8f"

logging:
  level:
    apps.sarafrika.elimika.common.security: INFO
    org.springframework.security: INFO
    org.springframework.web.filter: INFO
    root: DEBUG