package apps.sarafrika.elimika.classes.dto;

import apps.sarafrika.elimika.shared.enums.ClassVisibility;
import apps.sarafrika.elimika.shared.enums.LocationType;
import apps.sarafrika.elimika.shared.enums.SessionFormat;
import apps.sarafrika.elimika.shared.validation.ValidTimeRange;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.DecimalMin;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Positive;
import jakarta.validation.constraints.Size;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.List;
import java.util.UUID;

/**
 * Class Definition Data Transfer Object
 * <p>
 * Represents class definition templates in the Sarafrika Elimika system.
 * This defines "what" a class is, independent of "when" it occurs, including
 * content, format, capacity, and recurrence rules for the Timetabling module.
 *
 * @author Wilfred Njuguna
 * @version 1.0
 * @since 2024-09-05
 */
@Schema(
        name = "ClassDefinition",
        description = "Class definition template that defines what a class is, independent of scheduling",
        example = """
        {
            "uuid": "cd123456-7890-abcd-ef01-234567890abc",
            "title": "Introduction to Java Programming",
            "description": "Comprehensive introduction to Java programming covering basics, OOP concepts, and practical application development.",
            "default_instructor_uuid": "inst1234-5678-90ab-cdef-123456789abc",
            "organisation_uuid": "org12345-6789-abcd-ef01-234567890abc",
            "course_uuid": "course123-4567-89ab-cdef-123456789abc",
            "training_fee": 240.00,
            "class_visibility": "PUBLIC",
            "session_format": "GROUP",
            "default_start_time": "2025-01-15T14:00:00Z",
            "default_end_time": "2025-01-15T15:30:00Z",
            "duration_minutes": 90,
            "location_type": "HYBRID",
            "location_name": "Nairobi HQ – Room 101",
            "location_latitude": -1.292066,
            "location_longitude": 36.821945,
            "max_participants": 25,
            "allow_waitlist": true,
            "session_templates": [
              {
                "start_time": "2025-01-15T14:00:00Z",
                "end_time": "2025-01-15T15:30:00Z",
                "recurrence": {
                  "recurrence_type": "WEEKLY",
                  "interval_value": 1,
                  "days_of_week": "MONDAY,WEDNESDAY",
                  "occurrence_count": 8
                },
                "conflict_resolution": "FAIL"
              }
            ],
            "is_active": true,
            "created_date": "2024-09-05T10:00:00",
            "updated_date": "2024-09-05T15:30:00",
            "created_by": "admin@sarafrika.com",
            "updated_by": "admin@sarafrika.com"
        }
        """
)
@ValidTimeRange(
        startField = "defaultStartTime",
        endField = "defaultEndTime",
        message = "Class end time must be after start time"
)
public record ClassDefinitionDTO(

        @Schema(
                description = "**[READ-ONLY]** Unique system identifier for the class definition. Auto-generated by the system.",
                example = "cd123456-7890-abcd-ef01-234567890abc",
                accessMode = Schema.AccessMode.READ_ONLY,
                requiredMode = Schema.RequiredMode.NOT_REQUIRED
        )
        @JsonProperty(value = "uuid", access = JsonProperty.Access.READ_ONLY)
        UUID uuid,

        @Schema(
                description = "**[REQUIRED]** Title of the class definition. Used for identification and display.",
                example = "Introduction to Java Programming",
                maxLength = 255,
                requiredMode = Schema.RequiredMode.REQUIRED
        )
        @NotBlank(message = "Class title is required")
        @Size(max = 255, message = "Title must not exceed 255 characters")
        @JsonProperty("title")
        String title,

        @Schema(
                description = "**[OPTIONAL]** Detailed description of the class content, objectives, and what students will learn.",
                example = "Comprehensive introduction to Java programming covering basics, OOP concepts, and practical application development.",
                maxLength = 2000,
                nullable = true,
                requiredMode = Schema.RequiredMode.NOT_REQUIRED
        )
        @Size(max = 2000, message = "Description must not exceed 2000 characters")
        @JsonProperty("description")
        String description,

        @Schema(
                description = "**[REQUIRED]** Reference to the default instructor UUID for this class definition.",
                example = "inst1234-5678-90ab-cdef-123456789abc",
                requiredMode = Schema.RequiredMode.REQUIRED
        )
        @NotNull(message = "Default instructor UUID is required")
        @JsonProperty("default_instructor_uuid")
        UUID defaultInstructorUuid,

        @Schema(
                description = "**[OPTIONAL]** Reference to the organization UUID that owns this class definition.",
                example = "org12345-6789-abcd-ef01-234567890abc",
                nullable = true,
                requiredMode = Schema.RequiredMode.NOT_REQUIRED
        )
        @JsonProperty("organisation_uuid")
        UUID organisationUuid,

        @Schema(
                description = "**[OPTIONAL]** Reference to the course UUID if this class is part of a structured course.",
                example = "course123-4567-89ab-cdef-123456789abc",
                nullable = true,
                requiredMode = Schema.RequiredMode.NOT_REQUIRED
        )
        @JsonProperty("course_uuid")
        UUID courseUuid,

        @Schema(
                description = "**[OPTIONAL]** Training fee charged for sessions created from this class definition. Must meet the course minimum training fee when a course is linked.",
                example = "220.00",
                minimum = "0",
                nullable = true,
                requiredMode = Schema.RequiredMode.NOT_REQUIRED
        )
        @DecimalMin(value = "0.00", message = "Training fee cannot be negative")
        @JsonProperty("training_fee")
        BigDecimal trainingFee,

        @Schema(
                description = "**[REQUIRED]** Visibility of the class when offerings are published.",
                example = "PUBLIC",
                allowableValues = {"PUBLIC", "PRIVATE"},
                requiredMode = Schema.RequiredMode.REQUIRED
        )
        @NotNull(message = "Class visibility is required")
        @JsonProperty("class_visibility")
        ClassVisibility classVisibility,

        @Schema(
                description = "**[REQUIRED]** Session format indicating whether the delivery targets an individual learner or group.",
                example = "GROUP",
                allowableValues = {"INDIVIDUAL", "GROUP"},
                requiredMode = Schema.RequiredMode.REQUIRED
        )
        @NotNull(message = "Session format is required")
        @JsonProperty("session_format")
        SessionFormat sessionFormat,

        @Schema(
                description = "**[REQUIRED]** Default start date-time for class sessions (UTC).",
                example = "2025-01-15T09:00:00Z",
                format = "date-time",
                requiredMode = Schema.RequiredMode.REQUIRED
        )
        @NotNull(message = "Default start time is required")
        @JsonProperty("default_start_time")
        LocalDateTime defaultStartTime,

        @Schema(
                description = "**[REQUIRED]** Default end date-time for class sessions (UTC).",
                example = "2025-01-15T10:30:00Z",
                format = "date-time",
                requiredMode = Schema.RequiredMode.REQUIRED
        )
        @NotNull(message = "Default end time is required")
        @JsonProperty("default_end_time")
        LocalDateTime defaultEndTime,

        @Schema(
                description = "**[REQUIRED]** Default delivery format for the class.",
                example = "HYBRID",
                allowableValues = {"ONLINE", "IN_PERSON", "HYBRID"},
                requiredMode = Schema.RequiredMode.REQUIRED
        )
        @NotNull(message = "Location type is required")
        @JsonProperty("location_type")
        LocationType locationType,

        @Schema(
                description = "**[OPTIONAL]** Human-readable name for the primary class location, used for Mapbox forward/reverse geocoding (e.g., campus, room, or venue name). " +
                        "Required when location_type is IN_PERSON or HYBRID.",
                example = "Nairobi HQ – Room 101",
                maxLength = 255,
                nullable = true,
                requiredMode = Schema.RequiredMode.NOT_REQUIRED
        )
        @JsonProperty("location_name")
        String locationName,

        @Schema(
                description = "**[OPTIONAL]** Latitude coordinate for the primary class location, used with Mapbox. " +
                        "Required when location_type is IN_PERSON or HYBRID.",
                example = "-1.292066",
                nullable = true,
                requiredMode = Schema.RequiredMode.NOT_REQUIRED
        )
        @JsonProperty("location_latitude")
        BigDecimal locationLatitude,

        @Schema(
                description = "**[OPTIONAL]** Longitude coordinate for the primary class location, used with Mapbox. " +
                        "Required when location_type is IN_PERSON or HYBRID.",
                example = "36.821945",
                nullable = true,
                requiredMode = Schema.RequiredMode.NOT_REQUIRED
        )
        @JsonProperty("location_longitude")
        BigDecimal locationLongitude,

        @Schema(
                description = "**[OPTIONAL]** Maximum number of participants allowed in the class.",
                example = "25",
                minimum = "1",
                maximum = "1000",
                nullable = false,
                requiredMode = Schema.RequiredMode.NOT_REQUIRED
        )
        @Positive(message = "Max participants must be positive")
        @JsonProperty("max_participants")
        Integer maxParticipants,

        @Schema(
                description = "**[OPTIONAL]** Whether to allow waitlisting when maximum capacity is reached.",
                example = "true",
                nullable = false,
                requiredMode = Schema.RequiredMode.NOT_REQUIRED
        )
        @JsonProperty("allow_waitlist")
        Boolean allowWaitlist,

        @Schema(
                description = "**[OPTIONAL]** Whether this class definition is currently active and available for scheduling.",
                example = "true",
                nullable = false,
                requiredMode = Schema.RequiredMode.NOT_REQUIRED
        )
        @JsonProperty("is_active")
        Boolean isActive,

        @Schema(
                description = """
                        **[REQUIRED]** Inline session templates with time slots and recurrence rules to schedule class instances during creation.
                        conflict_resolution per template:
                        - FAIL: stop scheduling if any conflict; response 409 with conflicts.
                        - SKIP: schedule non-conflicting occurrences; return conflicts for skipped dates.
                        - ROLLOVER: push conflicting dates forward by the recurrence interval (bounded retries) and extend the series; return unrecoverable conflicts.
                        """,
                requiredMode = Schema.RequiredMode.REQUIRED
        )
        @JsonProperty("session_templates")
        @NotNull(message = "session_templates is required")
        @Size(min = 1, message = "At least one session template is required")
        List<ClassSessionTemplateDTO> sessionTemplates,

        @Schema(
                description = "**[READ-ONLY]** Timestamp when the class definition was first created. Automatically set by the system.",
                example = "2024-09-05T10:00:00",
                format = "date-time",
                accessMode = Schema.AccessMode.READ_ONLY,
                requiredMode = Schema.RequiredMode.NOT_REQUIRED
        )
        @JsonProperty(value = "created_date", access = JsonProperty.Access.READ_ONLY)
        LocalDateTime createdDate,

        @Schema(
                description = "**[READ-ONLY]** Timestamp when the class definition was last modified. Automatically updated by the system.",
                example = "2024-09-05T15:30:00",
                format = "date-time",
                accessMode = Schema.AccessMode.READ_ONLY,
                requiredMode = Schema.RequiredMode.NOT_REQUIRED
        )
        @JsonProperty(value = "updated_date", access = JsonProperty.Access.READ_ONLY)
        LocalDateTime updatedDate,

        @Schema(
                description = "**[READ-ONLY]** Email or username of the user who created this class definition.",
                example = "admin@sarafrika.com",
                accessMode = Schema.AccessMode.READ_ONLY,
                requiredMode = Schema.RequiredMode.NOT_REQUIRED
        )
        @JsonProperty(value = "created_by", access = JsonProperty.Access.READ_ONLY)
        String createdBy,

        @Schema(
                description = "**[READ-ONLY]** Email or username of the user who last modified this class definition.",
                example = "admin@sarafrika.com",
                accessMode = Schema.AccessMode.READ_ONLY,
                requiredMode = Schema.RequiredMode.NOT_REQUIRED
        )
        @JsonProperty(value = "updated_by", access = JsonProperty.Access.READ_ONLY)
        String updatedBy

) {

    /**
     * Returns the computed duration in minutes based on start and end times.
     *
     * @return Duration in minutes
     */
    @JsonProperty(value = "duration_minutes", access = JsonProperty.Access.READ_ONLY)
    @Schema(
            description = "**[READ-ONLY]** Computed duration of the class in minutes based on start and end times.",
            example = "90",
            accessMode = Schema.AccessMode.READ_ONLY
    )
    public long getDurationMinutes() {
        if (defaultStartTime == null || defaultEndTime == null) {
            return 0;
        }
        return java.time.Duration.between(defaultStartTime, defaultEndTime).toMinutes();
    }

    /**
     * Returns a formatted duration string.
     *
     * @return Human-readable duration format (e.g., "1h 30m", "45m")
     */
    @JsonProperty(value = "duration_formatted", access = JsonProperty.Access.READ_ONLY)
    @Schema(
            description = "**[READ-ONLY]** Human-readable formatted duration.",
            example = "1h 30m",
            accessMode = Schema.AccessMode.READ_ONLY
    )
    public String getDurationFormatted() {
        long durationMinutes = getDurationMinutes();
        if (durationMinutes <= 0) {
            return "0m";
        }

        long hours = durationMinutes / 60;
        long minutes = durationMinutes % 60;

        if (hours > 0 && minutes > 0) {
            return hours + "h " + minutes + "m";
        } else if (hours > 0) {
            return hours + "h";
        } else {
            return minutes + "m";
        }
    }

    /**
     * Checks if this is a standalone class (not part of a course).
     *
     * @return true if not associated with a course, false otherwise
     */
    @JsonProperty(value = "is_standalone", access = JsonProperty.Access.READ_ONLY)
    @Schema(
            description = "**[READ-ONLY]** Indicates if this is a standalone class not associated with any course.",
            example = "false",
            accessMode = Schema.AccessMode.READ_ONLY
    )
    public boolean isStandalone() {
        return courseUuid == null;
    }

    /**
     * Returns the capacity status description.
     *
     * @return Capacity description including waitlist availability
     */
    @JsonProperty(value = "capacity_info", access = JsonProperty.Access.READ_ONLY)
    @Schema(
            description = "**[READ-ONLY]** Human-readable capacity information including waitlist availability.",
            example = "Max 25 participants (waitlist enabled)",
            accessMode = Schema.AccessMode.READ_ONLY
    )
    public String getCapacityInfo() {
        if (maxParticipants == null || maxParticipants <= 0) {
            return "No capacity limit";
        }

        String baseInfo = "Max " + maxParticipants + " participants";
        if (Boolean.TRUE.equals(allowWaitlist)) {
            return baseInfo + " (waitlist enabled)";
        } else {
            return baseInfo + " (no waitlist)";
        }
    }
}
