### Get All Instructors
< {%
    client.global.clearAll()
%}
GET http://localhost:8080/api/v1/instructors?page=0&size=15
Accept: application/json

> {%
    let instructor = response.body["data"][0]

    if (instructor) {

        let instructorId = instructor.id
        client.global.set("instructor_id", instructorId)
    }
%}


### Create Course
POST http://localhost:8080/api/v1/courses
Content-Type: application/json

{
  "name": "Football",
  "description": "A comprehensive course on Football.",
  "difficultyLevel": "BEGINNER",
  "minAge": 15,
  "maxAge": 50
}

### Get All Courses
GET http://localhost:8080/api/v1/courses?page=0&size=15
Accept: application/json

> {%
    let courseId = response.body["data"][0].id

    client.global.set("courseId", courseId)
%}

### Get Course
GET http://localhost:8080/api/v1/courses/{{courseId}}
Accept: application/json

### Update Course
PUT http://localhost:8080/api/v1/courses/{{courseId}}
Content-Type: application/json

{
  "name": "Football",
  "description": "A comprehensive course on Football.",
  "difficultyLevel": "BEGINNER",
  "minAge": 15,
  "maxAge": 35
}

### Delete course
DELETE http://localhost:8080/api/v1/courses/{{courseId}}


### Create module
POST http://localhost:8080/api/v1/courses/{{courseId}}/modules
Content-Type: application/json

{
  "name": "Intermediate",
  "description": "A beginner's intro to music."
}

### Get All Modules
GET http://localhost:8080/api/v1/courses/{{courseId}}/modules?page=0&size=15
Accept: application/json

> {%
    let moduleId = response.body["data"][0].id

    client.global.set("moduleId", moduleId)
%}

### Create Lesson
POST http://localhost:8080/api/v1/courses/{{courseId}}/modules/{{moduleId}}/lessons
Content-Type: application/json

{
  "title": "Introduction to Music I",
  "description": "A beginner's intro to music.",
  "content": "A beginner's intro to music.",
  "lessonOrder": 1
}

### Get Lessons
GET http://localhost:8080/api/v1/courses/{{courseId}}/modules/{{moduleId}}/lessons?page=0&size=15
Accept: application/json

> {%
    let lessonId = response.body["data"][0].id

    client.global.set("lessonId", lessonId)
%}

### Create assessment
POST http://localhost:8080/api/v1/assessments
Content-Type: application/json

{
  "title": "Introduction to Music Quiz 1",
  "type": "Quiz",
  "description": "First assessment for the Introduction to Music course.",
  "maximumScore": 100,
  "passingScore": 40,
  "dueDate": "2024-09-13T00:00:00",
  "timeLimit": 60,
  "scope": "LESSON",
  "courseId": {{courseId}},
  "lessonId": {{lessonId}}
}


### Create Prerequisite Type
POST http://localhost:8080/api/v1/prerequisite-types
Content-Type: application/json

{
  "name": "course"
}

### Get Prerequisite Types
GET http://localhost:8080/api/v1/prerequisite-types?page=0&size=15
Accept: application/json

> {%
    let prerequisiteTypeId = response.body["data"][0].id

    client.global.set("prerequisiteTypeId", prerequisiteTypeId)
%}

### Create prerequisite
POST http://localhost:8080/api/v1/prerequisites
Content-Type: application/json

{
  "prerequisiteTypeId": {{prerequisiteTypeId}},
  "ownerType": "COURSE",
  "ownerId": {{courseId}},
  "requiredOwnerType": "MODULE",
  "requiredOwnerId": {{moduleId}},
  "minimumScore": 10
}

### Create Prerequisite Group
POST http://localhost:8080/api/v1/prerequisite-groups
Content-Type: application/json

{
  "ownerType": "COURSE",
  "ownerId": {{courseId}},
  "groupType": "COURSE",
  "prerequisiteIds": [
    {{prerequisiteId}}
  ]
}

