networks:
  sarafrika:
    external: true

volumes:
  elimika_storage:
    driver: local
  elimika_logs:
    driver: local

services:
  elimika:
    image: sarafrika/elimika:latest
    restart: unless-stopped
    env_file:
      - .env
    environment:
      SERVER_PORT: 30000
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "30000:30000"
    networks:
      - sarafrika
    volumes:
      - elimika_storage:/app/storage
      - elimika_logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:30000/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s