version: '3.8'

networks:
  sarafrika:
    external: true

services:
  elimika:
    image: sarafrika/elimika:latest
    restart: unless-stopped
    env_file:
      - .env
    environment:
      SERVER_PORT: 30000
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "30000:30000"
    networks:
      - sarafrika