-- The marketplace funnel now ends in a hire: HIRED replaced APPROVED in
-- ClassMarketplaceJobApplicationStatus, but chk_class_marketplace_job_applications_status was last
-- written by V202608131300 and still enumerated 'APPROVED', so the very first hire failed.
--
-- Approval was never a commitment - it stamped neither the job nor the instructor's affiliation -
-- so an approved row is not relabelled a hire. It goes back to OFFERED, the one live stage HIRED is
-- reachable from, and the organisation finishes the hire through the path that does affiliate.
--
-- An approval on a job since filled, cancelled or expired was already closed to NOT_SELECTED, so
-- only live funnels are touched. The rewrite sits between the two constraints because neither the
-- old set nor the new one admits both spellings at once.

ALTER TABLE class_marketplace_job_applications
    DROP CONSTRAINT IF EXISTS chk_class_marketplace_job_applications_status;

UPDATE class_marketplace_job_applications
SET status = 'OFFERED'
WHERE status = 'APPROVED';

ALTER TABLE class_marketplace_job_applications
    ADD CONSTRAINT chk_class_marketplace_job_applications_status
        CHECK (status IN (
            'PENDING', 'SHORTLISTED', 'INTERVIEWING', 'OFFERED',
            'HIRED', 'REJECTED', 'ASSIGNED', 'NOT_SELECTED', 'WITHDRAWN'
        ));

-- The notification that announces the decision was renamed with it, from
-- CLASS_MARKETPLACE_JOB_APPLICATION_APPROVED to CLASS_MARKETPLACE_JOB_APPLICATION_HIRED. Here the
-- rows ARE rewritten: the message was sent under its own stored title and body, and only the type
-- key moves - left behind it is an inbox entry the enum can no longer resolve.
--
-- Same sandwich as above: the live constraints (V202609021900) admit only the old name and the new
-- ones only the new name, so the rewrite belongs between the drops and the adds.

ALTER TABLE user_notifications
    DROP CONSTRAINT IF EXISTS chk_user_notifications_type;

ALTER TABLE notification_delivery_log
    DROP CONSTRAINT IF EXISTS chk_notification_type;

UPDATE user_notifications
SET notification_type = 'CLASS_MARKETPLACE_JOB_APPLICATION_HIRED'
WHERE notification_type = 'CLASS_MARKETPLACE_JOB_APPLICATION_APPROVED';

UPDATE notification_delivery_log
SET notification_type = 'CLASS_MARKETPLACE_JOB_APPLICATION_HIRED'
WHERE notification_type = 'CLASS_MARKETPLACE_JOB_APPLICATION_APPROVED';

ALTER TABLE user_notifications
    ADD CONSTRAINT chk_user_notifications_type CHECK (notification_type IN (
        'COURSE_ENROLLMENT_WELCOME', 'COURSE_COMPLETION_CERTIFICATE', 'LEARNING_MILESTONE_ACHIEVED',
        'ASSIGNMENT_DUE_REMINDER', 'ASSIGNMENT_SUBMITTED_CONFIRMATION', 'ASSIGNMENT_GRADED',
        'ASSIGNMENT_RETURNED_FOR_REVISION', 'ASSIGNMENT_DEADLINE_REMINDER', 'ASSESSMENT_COMPLETED',
        'NEW_STUDENT_ENROLLMENT', 'NEW_ASSIGNMENT_SUBMISSION', 'CLASS_SCHEDULE_UPDATED', 'GRADING_REMINDER',
        'COURSE_CONTENT_APPROVED', 'COURSE_CONTENT_REJECTED', 'PROGRAM_CONTENT_APPROVED',
        'PROGRAM_CONTENT_REJECTED', 'COURSE_TRAINING_APPLICATION_SUBMITTED',
        'COURSE_TRAINING_APPLICATION_APPROVED', 'COURSE_TRAINING_APPLICATION_REJECTED',
        'COURSE_TRAINING_APPLICATION_REVOKED', 'PROGRAM_TRAINING_APPLICATION_SUBMITTED',
        'PROGRAM_TRAINING_APPLICATION_APPROVED', 'PROGRAM_TRAINING_APPLICATION_REJECTED',
        'PROGRAM_TRAINING_APPLICATION_REVOKED', 'CLASS_MARKETPLACE_JOB_APPLICATION_REJECTED',
        'CLASS_MARKETPLACE_JOB_APPLICATION_NOT_SELECTED', 'CLASS_MARKETPLACE_JOB_EXPIRED',
        'CLASS_MARKETPLACE_JOB_APPLICATION_SHORTLISTED', 'CLASS_MARKETPLACE_JOB_APPLICATION_INTERVIEWING',
        'CLASS_MARKETPLACE_JOB_APPLICATION_OFFERED', 'CLASS_MARKETPLACE_JOB_APPLICATION_HIRED',
        'CLASS_MARKETPLACE_JOB_APPLICATION_ASSIGNED', 'CLASS_MARKETPLACE_JOB_APPLICATION_CANCELLED',
        'CLASS_MARKETPLACE_JOB_APPLICATION_WITHDRAWN', 'CLASS_ENROLLMENT_CONFIRMED',
        'COURSE_ENROLLMENT_MILESTONE', 'COURSE_ENROLLMENT_NOTICE', 'INSTRUCTOR_CLASS_ENROLLMENT_MILESTONE',
        'INSTRUCTOR_CLASS_ENROLLMENT_NOTICE', 'UPCOMING_CLASS_REMINDER', 'COURSE_REVIEW_SUBMITTED',
        'PROGRAM_REVIEW_SUBMITTED', 'CLASS_REVIEW_SUBMITTED', 'INSTRUCTOR_REVIEW_SUBMITTED',
        'ACCOUNT_CREATED', 'PASSWORD_RESET_REQUEST', 'SECURITY_ALERT', 'ORDER_PAYMENT_RECEIPT',
        'LEARNING_CERTIFICATE_ISSUED', 'PROFILE_DOCUMENT_VERIFIED', 'INSTRUCTOR_VERIFICATION_APPROVED',
        'INSTRUCTOR_VERIFICATION_REVOKED', 'COURSE_CREATOR_VERIFICATION_APPROVED',
        'COURSE_CREATOR_VERIFICATION_REVOKED', 'ORGANISATION_VERIFICATION_APPROVED',
        'ORGANISATION_VERIFICATION_REVOKED', 'PROFILE_COMPLETION_REMINDER', 'ORGANISATION_INVITATION',
        'GUARDIAN_CONSENT_REQUEST', 'ORGANISATION_INVITATION_ACCEPTED', 'WEEKLY_PROGRESS_SUMMARY',
        'LEARNING_STREAK_ACHIEVEMENT', 'PEER_ACHIEVEMENT_CELEBRATION', 'ORGANISATION_ANNOUNCEMENT'
    ));

ALTER TABLE notification_delivery_log
    ADD CONSTRAINT chk_notification_type CHECK (notification_type IN (
        'COURSE_ENROLLMENT_WELCOME', 'COURSE_COMPLETION_CERTIFICATE', 'LEARNING_MILESTONE_ACHIEVED',
        'ASSIGNMENT_DUE_REMINDER', 'ASSIGNMENT_SUBMITTED_CONFIRMATION', 'ASSIGNMENT_GRADED',
        'ASSIGNMENT_RETURNED_FOR_REVISION', 'ASSIGNMENT_DEADLINE_REMINDER', 'ASSESSMENT_COMPLETED',
        'NEW_STUDENT_ENROLLMENT', 'NEW_ASSIGNMENT_SUBMISSION', 'CLASS_SCHEDULE_UPDATED', 'GRADING_REMINDER',
        'COURSE_CONTENT_APPROVED', 'COURSE_CONTENT_REJECTED', 'PROGRAM_CONTENT_APPROVED',
        'PROGRAM_CONTENT_REJECTED', 'COURSE_TRAINING_APPLICATION_SUBMITTED',
        'COURSE_TRAINING_APPLICATION_APPROVED', 'COURSE_TRAINING_APPLICATION_REJECTED',
        'COURSE_TRAINING_APPLICATION_REVOKED', 'PROGRAM_TRAINING_APPLICATION_SUBMITTED',
        'PROGRAM_TRAINING_APPLICATION_APPROVED', 'PROGRAM_TRAINING_APPLICATION_REJECTED',
        'PROGRAM_TRAINING_APPLICATION_REVOKED', 'CLASS_MARKETPLACE_JOB_APPLICATION_REJECTED',
        'CLASS_MARKETPLACE_JOB_APPLICATION_NOT_SELECTED', 'CLASS_MARKETPLACE_JOB_EXPIRED',
        'CLASS_MARKETPLACE_JOB_APPLICATION_SHORTLISTED', 'CLASS_MARKETPLACE_JOB_APPLICATION_INTERVIEWING',
        'CLASS_MARKETPLACE_JOB_APPLICATION_OFFERED', 'CLASS_MARKETPLACE_JOB_APPLICATION_HIRED',
        'CLASS_MARKETPLACE_JOB_APPLICATION_ASSIGNED', 'CLASS_MARKETPLACE_JOB_APPLICATION_CANCELLED',
        'CLASS_MARKETPLACE_JOB_APPLICATION_WITHDRAWN', 'CLASS_ENROLLMENT_CONFIRMED',
        'COURSE_ENROLLMENT_MILESTONE', 'COURSE_ENROLLMENT_NOTICE', 'INSTRUCTOR_CLASS_ENROLLMENT_MILESTONE',
        'INSTRUCTOR_CLASS_ENROLLMENT_NOTICE', 'UPCOMING_CLASS_REMINDER', 'COURSE_REVIEW_SUBMITTED',
        'PROGRAM_REVIEW_SUBMITTED', 'CLASS_REVIEW_SUBMITTED', 'INSTRUCTOR_REVIEW_SUBMITTED',
        'ACCOUNT_CREATED', 'PASSWORD_RESET_REQUEST', 'SECURITY_ALERT', 'ORDER_PAYMENT_RECEIPT',
        'LEARNING_CERTIFICATE_ISSUED', 'PROFILE_DOCUMENT_VERIFIED', 'INSTRUCTOR_VERIFICATION_APPROVED',
        'INSTRUCTOR_VERIFICATION_REVOKED', 'COURSE_CREATOR_VERIFICATION_APPROVED',
        'COURSE_CREATOR_VERIFICATION_REVOKED', 'ORGANISATION_VERIFICATION_APPROVED',
        'ORGANISATION_VERIFICATION_REVOKED', 'PROFILE_COMPLETION_REMINDER', 'ORGANISATION_INVITATION',
        'GUARDIAN_CONSENT_REQUEST', 'ORGANISATION_INVITATION_ACCEPTED', 'WEEKLY_PROGRESS_SUMMARY',
        'LEARNING_STREAK_ACHIEVEMENT', 'PEER_ACHIEVEMENT_CELEBRATION', 'ORGANISATION_ANNOUNCEMENT'
    ));
