-- Create managed currencies table with auditing metadata
CREATE TABLE currencies
(
    id              BIGSERIAL PRIMARY KEY,
    uuid            UUID                     NOT NULL DEFAULT gen_random_uuid(),
    code            VARCHAR(3)               NOT NULL,
    numeric_code    INTEGER,
    currency_name   VARCHAR(128)             NOT NULL,
    symbol          VARCHAR(16),
    decimal_places  INTEGER                  NOT NULL DEFAULT 2,
    active          BOOLEAN                  NOT NULL DEFAULT TRUE,
    is_default      BOOLEAN                  NOT NULL DEFAULT FALSE,
    created_date    TIMESTAMP                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_date    TIMESTAMP,
    created_by      VARCHAR(255)             NOT NULL DEFAULT 'SYSTEM',
    updated_by      VARCHAR(255),
    CONSTRAINT uq_currencies_code UNIQUE (code),
    CONSTRAINT chk_currencies_decimal_places CHECK (decimal_places >= 0)
);

CREATE UNIQUE INDEX uq_currencies_default_true ON currencies (is_default) WHERE is_default;

-- Seed ISO-4217 currencies recognised by the platform (including historic codes for compatibility)
WITH seed_data(code, numeric_code, currency_name, decimal_places) AS (
    VALUES
('ADP', 20, 'Andorran Peseta', 0),
('AED', 784, 'United Arab Emirates Dirham', 2),
('AFA', 4, 'Afghan Afghani', 2),
('AFN', 971, 'Afghan Afghani', 2),
('ALL', 8, 'Albanian Lek', 2),
('AMD', 51, 'Armenian Dram', 2),
('ANG', 532, 'Netherlands Antillean Guilder', 2),
('AOA', 973, 'Angolan Kwanza', 2),
('ARS', 32, 'Argentine Peso', 2),
('ATS', 40, 'Austrian Schilling', 2),
('AUD', 36, 'Australian Dollar', 2),
('AWG', 533, 'Aruban Florin', 2),
('AYM', 945, 'AYM', 2),
('AZM', 31, 'Azerbaijani Manat', 2),
('AZN', 944, 'Azerbaijani Manat', 2),
('BAM', 977, 'Bosnia-Herzegovina Convertible Mark', 2),
('BBD', 52, 'Barbadian Dollar', 2),
('BDT', 50, 'Bangladeshi Taka', 2),
('BEF', 56, 'Belgian Franc', 0),
('BGL', 100, 'Bulgarian Hard Lev', 2),
('BGN', 975, 'Bulgarian Lev', 2),
('BHD', 48, 'Bahraini Dinar', 3),
('BIF', 108, 'Burundian Franc', 0),
('BMD', 60, 'Bermudan Dollar', 2),
('BND', 96, 'Brunei Dollar', 2),
('BOB', 68, 'Bolivian Boliviano', 2),
('BOV', 984, 'Bolivian Mvdol', 2),
('BRL', 986, 'Brazilian Real', 2),
('BSD', 44, 'Bahamian Dollar', 2),
('BTN', 64, 'Bhutanese Ngultrum', 2),
('BWP', 72, 'Botswanan Pula', 2),
('BYB', 112, 'Belarusian Ruble', 0),
('BYN', 933, 'Belarusian Ruble', 2),
('BYR', 974, 'Belarusian Ruble', 0),
('BZD', 84, 'Belize Dollar', 2),
('CAD', 124, 'Canadian Dollar', 2),
('CDF', 976, 'Congolese Franc', 2),
('CHE', 947, 'WIR Euro', 2),
('CHF', 756, 'Swiss Franc', 2),
('CHW', 948, 'WIR Franc', 2),
('CLF', 990, 'Chilean Unit of Account', 4),
('CLP', 152, 'Chilean Peso', 0),
('CNY', 156, 'Chinese Yuan', 2),
('COP', 170, 'Colombian Peso', 2),
('COU', 970, 'Colombian Real Value Unit', 2),
('CRC', 188, 'Costa Rican Colon', 2),
('CSD', 891, 'Serbian Dinar', 2),
('CUC', 931, 'Cuban Convertible Peso', 2),
('CUP', 192, 'Cuban Peso', 2),
('CVE', 132, 'Cape Verdean Escudo', 2),
('CYP', 196, 'Cypriot Pound', 2),
('CZK', 203, 'Czech Koruna', 2),
('DEM', 276, 'German Mark', 2),
('DJF', 262, 'Djiboutian Franc', 0),
('DKK', 208, 'Danish Krone', 2),
('DOP', 214, 'Dominican Peso', 2),
('DZD', 12, 'Algerian Dinar', 2),
('EEK', 233, 'Estonian Kroon', 2),
('EGP', 818, 'Egyptian Pound', 2),
('ERN', 232, 'Eritrean Nakfa', 2),
('ESP', 724, 'Spanish Peseta', 0),
('ETB', 230, 'Ethiopian Birr', 2),
('EUR', 978, 'Euro', 2),
('FIM', 246, 'Finnish Markka', 2),
('FJD', 242, 'Fijian Dollar', 2),
('FKP', 238, 'Falkland Islands Pound', 2),
('FRF', 250, 'French Franc', 2),
('GBP', 826, 'British Pound', 2),
('GEL', 981, 'Georgian Lari', 2),
('GHC', 288, 'Ghanaian Cedi', 2),
('GHS', 936, 'Ghanaian Cedi', 2),
('GIP', 292, 'Gibraltar Pound', 2),
('GMD', 270, 'Gambian Dalasi', 2),
('GNF', 324, 'Guinean Franc', 0),
('GRD', 300, 'Greek Drachma', 0),
('GTQ', 320, 'Guatemalan Quetzal', 2),
('GWP', 624, 'Guinea-Bissau Peso', 2),
('GYD', 328, 'Guyanaese Dollar', 2),
('HKD', 344, 'Hong Kong Dollar', 2),
('HNL', 340, 'Honduran Lempira', 2),
('HRK', 191, 'Croatian Kuna', 2),
('HTG', 332, 'Haitian Gourde', 2),
('HUF', 348, 'Hungarian Forint', 2),
('IDR', 360, 'Indonesian Rupiah', 2),
('IEP', 372, 'Irish Pound', 2),
('ILS', 376, 'Israeli New Shekel', 2),
('INR', 356, 'Indian Rupee', 2),
('IQD', 368, 'Iraqi Dinar', 3),
('IRR', 364, 'Iranian Rial', 2),
('ISK', 352, 'Icelandic Krona', 0),
('ITL', 380, 'Italian Lira', 0),
('JMD', 388, 'Jamaican Dollar', 2),
('JOD', 400, 'Jordanian Dinar', 3),
('JPY', 392, 'Japanese Yen', 0),
('KES', 404, 'Kenyan Shilling', 2),
('KGS', 417, 'Kyrgystani Som', 2),
('KHR', 116, 'Cambodian Riel', 2),
('KMF', 174, 'Comorian Franc', 0),
('KPW', 408, 'North Korean Won', 2),
('KRW', 410, 'South Korean Won', 0),
('KWD', 414, 'Kuwaiti Dinar', 3),
('KYD', 136, 'Cayman Islands Dollar', 2),
('KZT', 398, 'Kazakhstani Tenge', 2),
('LAK', 418, 'Laotian Kip', 2),
('LBP', 422, 'Lebanese Pound', 2),
('LKR', 144, 'Sri Lankan Rupee', 2),
('LRD', 430, 'Liberian Dollar', 2),
('LSL', 426, 'Lesotho Loti', 2),
('LTL', 440, 'Lithuanian Litas', 2),
('LUF', 442, 'Luxembourgian Franc', 0),
('LVL', 428, 'Latvian Lats', 2),
('LYD', 434, 'Libyan Dinar', 3),
('MAD', 504, 'Moroccan Dirham', 2),
('MDL', 498, 'Moldovan Leu', 2),
('MGA', 969, 'Malagasy Ariary', 2),
('MGF', 450, 'Malagasy Franc', 0),
('MKD', 807, 'Macedonian Denar', 2),
('MMK', 104, 'Myanmar Kyat', 2),
('MNT', 496, 'Mongolian Tugrik', 2),
('MOP', 446, 'Macanese Pataca', 2),
('MRO', 478, 'Mauritanian Ouguiya', 2),
('MRU', 929, 'Mauritanian Ouguiya', 2),
('MTL', 470, 'Maltese Lira', 2),
('MUR', 480, 'Mauritian Rupee', 2),
('MVR', 462, 'Maldivian Rufiyaa', 2),
('MWK', 454, 'Malawian Kwacha', 2),
('MXN', 484, 'Mexican Peso', 2),
('MXV', 979, 'Mexican Investment Unit', 2),
('MYR', 458, 'Malaysian Ringgit', 2),
('MZM', 508, 'Mozambican Metical', 2),
('MZN', 943, 'Mozambican Metical', 2),
('NAD', 516, 'Namibian Dollar', 2),
('NGN', 566, 'Nigerian Naira', 2),
('NIO', 558, 'Nicaraguan Cordoba', 2),
('NLG', 528, 'Dutch Guilder', 2),
('NOK', 578, 'Norwegian Krone', 2),
('NPR', 524, 'Nepalese Rupee', 2),
('NZD', 554, 'New Zealand Dollar', 2),
('OMR', 512, 'Omani Rial', 3),
('PAB', 590, 'Panamanian Balboa', 2),
('PEN', 604, 'Peruvian Sol', 2),
('PGK', 598, 'Papua New Guinean Kina', 2),
('PHP', 608, 'Philippine Peso', 2),
('PKR', 586, 'Pakistani Rupee', 2),
('PLN', 985, 'Polish Zloty', 2),
('PTE', 620, 'Portuguese Escudo', 0),
('PYG', 600, 'Paraguayan Guarani', 0),
('QAR', 634, 'Qatari Riyal', 2),
('ROL', 642, 'Romanian Leu', 0),
('RON', 946, 'Romanian Leu', 2),
('RSD', 941, 'Serbian Dinar', 2),
('RUB', 643, 'Russian Ruble', 2),
('RUR', 810, 'Russian Ruble', 2),
('RWF', 646, 'Rwandan Franc', 0),
('SAR', 682, 'Saudi Riyal', 2),
('SBD', 90, 'Solomon Islands Dollar', 2),
('SCR', 690, 'Seychellois Rupee', 2),
('SDD', 736, 'Sudanese Dinar', 2),
('SDG', 938, 'Sudanese Pound', 2),
('SEK', 752, 'Swedish Krona', 2),
('SGD', 702, 'Singapore Dollar', 2),
('SHP', 654, 'St. Helena Pound', 2),
('SIT', 705, 'Slovenian Tolar', 2),
('SKK', 703, 'Slovak Koruna', 2),
('SLE', 925, 'Sierra Leonean Leone', 2),
('SLL', 694, 'Sierra Leonean Leone', 2),
('SOS', 706, 'Somali Shilling', 2),
('SRD', 968, 'Surinamese Dollar', 2),
('SRG', 740, 'Surinamese Guilder', 2),
('SSP', 728, 'South Sudanese Pound', 2),
('STD', 678, 'Sao Tome & Principe Dobra', 2),
('STN', 930, 'Sao Tome & Principe Dobra', 2),
('SVC', 222, 'Salvadoran Colon', 2),
('SYP', 760, 'Syrian Pound', 2),
('SZL', 748, 'Swazi Lilangeni', 2),
('THB', 764, 'Thai Baht', 2),
('TJS', 972, 'Tajikistani Somoni', 2),
('TMM', 795, 'Turkmenistani Manat', 2),
('TMT', 934, 'Turkmenistani Manat', 2),
('TND', 788, 'Tunisian Dinar', 3),
('TOP', 776, 'Tongan Pa''anga', 2),
('TPE', 626, 'Timorese Escudo', 0),
('TRL', 792, 'Turkish Lira', 0),
('TRY', 949, 'Turkish Lira', 2),
('TTD', 780, 'Trinidad & Tobago Dollar', 2),
('TWD', 901, 'New Taiwan Dollar', 2),
('TZS', 834, 'Tanzanian Shilling', 2),
('UAH', 980, 'Ukrainian Hryvnia', 2),
('UGX', 800, 'Ugandan Shilling', 0),
('USD', 840, 'US Dollar', 2),
('USN', 997, 'US Dollar', 2),
('USS', 998, 'US Dollar', 2),
('UYI', 940, 'Uruguayan Peso', 0),
('UYU', 858, 'Uruguayan Peso', 2),
('UZS', 860, 'Uzbekistani Som', 2),
('VEB', 862, 'Venezuelan Bolivar', 2),
('VED', 926, 'Bolivar Soberano', 2),
('VEF', 937, 'Venezuelan Bolivar', 2),
('VES', 928, 'Venezuelan Bolivar', 2),
('VND', 704, 'Vietnamese Dong', 0),
('VUV', 548, 'Vanuatu Vatu', 0),
('WST', 882, 'Samoan Tala', 2),
('XAD', 396, 'Arab Accounting Dinar', 2),
('XAF', 950, 'Central African CFA Franc', 0),
('XAG', 961, 'Silver', -1),
('XAU', 959, 'Gold', -1),
('XBA', 955, 'European Composite Unit', -1),
('XBB', 956, 'European Monetary Unit', -1),
('XBC', 957, 'European Unit of Account', -1),
('XBD', 958, 'European Unit of Account', -1),
('XCD', 951, 'East Caribbean Dollar', 2),
('XCG', 532, 'Caribbean Guilder', 2),
('XDR', 960, 'Special Drawing Rights', -1),
('XFO', 0, 'French Gold Franc', -1),
('XFU', 0, 'French UIC-Franc', -1),
('XOF', 952, 'West African CFA Franc', 0),
('XPD', 964, 'Palladium', -1),
('XPF', 953, 'CFP Franc', 0),
('XPT', 962, 'Platinum', -1),
('XSU', 994, 'Sucre', -1),
('XTS', 963, 'Testing Currency Code', -1),
('XUA', 965, 'ADB Unit of Account', -1),
('XXX', 999, 'Unknown Currency', -1),
('YER', 886, 'Yemeni Rial', 2),
('YUM', 891, 'Yugoslavian New Dinar', 2),
('ZAR', 710, 'South African Rand', 2),
('ZMK', 894, 'Zambian Kwacha', 2),
('ZMW', 967, 'Zambian Kwacha', 2),
('ZWD', 716, 'Zimbabwean Dollar', 2),
('ZWG', 924, 'Zimbabwe Gold', 2),
('ZWL', 932, 'Zimbabwean Dollar', 2),
('ZWN', 942, 'ZWN', 2),
('ZWR', 935, 'Zimbabwean Dollar', 2),

)
INSERT INTO currencies (code, numeric_code, currency_name, decimal_places, active, is_default, created_by)
SELECT code,
       numeric_code,
       currency_name,
       decimal_places,
       CASE WHEN code = 'KES' THEN TRUE ELSE FALSE END,
       CASE WHEN code = 'KES' THEN TRUE ELSE FALSE END,
       'SYSTEM'
FROM seed_data;

-- Ensure non-default currencies are inactive until explicitly enabled
UPDATE currencies
SET active = FALSE
WHERE code <> 'KES';

-- Align existing references to use managed currencies
UPDATE commerce_catalog_item
SET currency_code = 'KES'
WHERE currency_code IS NULL OR currency_code = '';

ALTER TABLE commerce_catalog_item
    ALTER COLUMN currency_code TYPE VARCHAR(3),
    ALTER COLUMN currency_code SET NOT NULL,
    ALTER COLUMN currency_code SET DEFAULT 'KES';

UPDATE commerce_catalog_item
SET currency_code = UPPER(currency_code);

ALTER TABLE commerce_catalog_item
    ADD CONSTRAINT fk_catalog_currency FOREIGN KEY (currency_code) REFERENCES currencies (code);

UPDATE course_training_applications
SET rate_currency = 'KES'
WHERE rate_currency IS NULL OR rate_currency = '';

ALTER TABLE course_training_applications
    ALTER COLUMN rate_currency TYPE VARCHAR(3),
    ALTER COLUMN rate_currency SET NOT NULL,
    ALTER COLUMN rate_currency SET DEFAULT 'KES';

UPDATE course_training_applications
SET rate_currency = UPPER(rate_currency);

ALTER TABLE course_training_applications
    ADD CONSTRAINT fk_course_training_application_currency FOREIGN KEY (rate_currency) REFERENCES currencies (code);
