-- Add ORDER_PAYMENT_RECEIPT notification type for receipts/invoices

ALTER TABLE notification_delivery_log
    DROP CONSTRAINT IF EXISTS chk_notification_type;

ALTER TABLE notification_delivery_log
    ADD CONSTRAINT chk_notification_type CHECK (notification_type IN (
        'COURSE_ENROLLMENT_WELCOME',
        'COURSE_COMPLETION_CERTIFICATE',
        'LEARNING_MILESTONE_ACHIEVED',
        'ASSIGNMENT_DUE_REMINDER',
        'ASSIGNMENT_SUBMITTED_CONFIRMATION',
        'ASSIGNMENT_GRADED',
        'ASSIGNMENT_RETURNED_FOR_REVISION',
        'NEW_STUDENT_ENROLLMENT',
        'NEW_ASSIGNMENT_SUBMISSION',
        'GRADING_REMINDER',
        'USER_INVITATION_SENT',
        'INVITATION_ACCEPTED',
        'INVITATION_DECLINED',
        'INVITATION_EXPIRY_REMINDER',
        'ACCOUNT_CREATED',
        'PASSWORD_RESET_REQUEST',
        'SECURITY_ALERT',
        'ORDER_PAYMENT_RECEIPT',
        'WEEKLY_PROGRESS_SUMMARY',
        'LEARNING_STREAK_ACHIEVEMENT',
        'PEER_ACHIEVEMENT_CELEBRATION'
    ));
