name: Docker Build and Push

on:
  pull_request:
    branches:
      - main
    types:
      - closed  # Only trigger when PR is merged into main
  push:
    branches:
      - main


  push:
    branches:
      - main

jobs:
  build-and-push:
    if: github.event.pull_request.merged == true  # Run only when a PR is merged into main
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-${{ runner.os }}

      - name: Extract Application Version
        id: get_version
        run: echo "APP_VERSION=$(./gradlew properties --no-daemon | grep "version:" | awk '{print $2}')" >> $GITHUB_ENV

      - name: Build JAR file with Gradle
        run: ./gradlew clean build -x test

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and tag Docker image with version
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/elimika:${{ env.APP_VERSION }} .
          docker tag ${{ secrets.DOCKER_USERNAME }}/elimika:${{ env.APP_VERSION }} ${{ secrets.DOCKER_USERNAME }}/elimika:latest

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/elimika:${{ env.APP_VERSION }}
          docker push ${{ secrets.DOCKER_USERNAME }}/elimika:latest
